[workspace]
members = [
    # Apps
    "crates/apps/interactive_shell",

    # Core
    "crates/core/orchestrator",
    "crates/core/flow_engine",

    # Producers
    "crates/plugins/producers/binance_gateway",
    "crates/plugins/producers/ohlcv_fetcher",
    "crates/plugins/producers/oi_fetcher",

    # Analytics & Strategies
    "crates/plugins/analytics/plugin_aggtrade_stats",
    "crates/plugins/analytics/plugin_aggtrade_ohlcv",
    "crates/plugins/analytics/plugin_bookticker_derivatives",
    "crates/plugins/analytics/plugin_amihud",
    "crates/plugins/analytics/plugin_spoofing",
    "crates/plugins/analytics/plugin_iceberg",
    "crates/plugins/analytics/plugin_absorption",
    "crates/plugins/analytics/plugin_sys_metrics",
    "crates/plugins/analytics/ms_analyzer",
    "crates/plugins/analytics/plugin_breakout",
    "crates/plugins/analytics/plugin_scout",

    # Execution
    "crates/plugins/execution/binance_trader",
    "crates/plugins/execution/plugin_paper_exchange",

    # Storage
    "crates/plugins/storage/plugin_binance_sqlite",
    "crates/plugins/storage/plugin_sqlite_query",
]
resolver = "2"

