[workspace]
members = [
    "orchestrator",
    "plugin_aggtrade",
    "plugin_alarm",
    "plugin_binance",
    "plugin_depth",
    "plugin_liquidation",
    "plugin_msmp",
    "plugin_msmp_requester",
    "plugin_ohlcv_fetcher",
    "plugin_ohlcv_requester",
    "plugin_storage",
    "plugin_timescaledb",
    "plugin_tps",
    "plugin_validator"
]
resolver = "2"
